---

- hosts: all
  vars:
    users: # tambahin user disini
    - "john"
    - "test1"
    - "test2"
    - "test3"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "admin"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.pub') }}"
    with_items: "{{ users }}"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
