name: "Ansible Run"

on:
  push:
    branches: [ master ]

jobs:
  ansiblerun:
    name: Ansible Run
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Run out code 
      uses: actions/checkout@v3
    - name: Run
      run: |
        echo "${{ secrets.ANSIBLE_INVENTORY }}" > hosts
        ls -lah
    - name: Ansible check
      uses: tomasnorre/ansible-cli-action@0.0.5
      with:
        command: "ansible-playbook -i hosts all.yaml"
