name: "Ansible Run"

on:
  push:
    branches: [ master ]

jobs:
  ansiblerun:
    name: Ansible Run
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Run out code 
      uses: actions/checkout@v3
    - name: Run
      run: |
        echo "${{ secrets.ANSIBLE_INVENTORY }}" > hosts
        ls -lah
        sudo apt update
        sudo apt install software-properties-common -y
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible
        ansible-playbook -i hosts all.yaml
